services:
  web-app:
    image: knivesh1/express-app:latest
    container_name: express-development
    restart: always
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

